[package]
name = "old-example-raw"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
reverie-engine-opengl.workspace = true

c_str_macro = "1.0.3"
