[package]
name = "example-window"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
reverie-engine-opengl.workspace = true
