[package]
name = "example-raw"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
c_str_macro.workspace = true
reverie-engine.workspace = true
