[package]
name = "example-raw"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
c_str_macro.workspace = true
reverie-engine-opengl.workspace = true
