[package]
name = "old-example-window"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
reverie-engine-opengl.workspace = true
