[package]
name = "reverie-util"
version = "0.0.0"
license = "MPL-2.0"
edition = "2021"
authors  = ["yuma140902 <yuma140902@gmail.com>"]
description = "Utilities for reverie-engine"
readme = "reverie-util/README.md"
repository = "https://github.com/yuma140902/Reverie"
categories = ["game-development"]

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-pc-windows-msvc"

[dependencies]
approx = "0.5.1"
nalgebra = "0.31.1"
newtype-ops = "0.1.4"
