[package]
name = "example-yagami-craft"
version = "0.1.0"
edition = "2018"

[dependencies]
reverie-engine = { version = "0.0.5", path = "../../reverie" }
nalgebra = "0.31.1"
nalgebra-glm = "0.17.0"
c_str_macro = "1.0.3"
image = "0.24.3"
glutin = "0.29.1"
winit = "0.27.3"
