style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/yuma140902/Reverie
options:
  tag_filter_pattern: '^util-v'
  commits:
     filters:
       Scope:
         - util
  commit_groups:
    # title_maps:
    #   feat: Features
    #   fix: Bug Fixes
    #   perf: Performance Improvements
    #   refactor: Code Refactoring
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\!?:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject

  merges:
    pattern: "^Merge pull request #[0-9]+ from '?(\\w+)/(util-\\w+)'?$"
    pattern_maps:
      - Contributor
      - Source

  notes:
    keywords:
      - BREAKING CHANGE
