[package]
name = "example-craft"
version = "0.1.0"
edition = "2018"

[dependencies]
reverie-engine = { path = "../../reverie" }
nalgebra = { version = "0.31.1", features = ["serde-serialize"] }
nalgebra-glm = "0.17.0"
c_str_macro = "1.0.3"
image = "0.24.3"
parry3d = "0.9.0"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
once_cell = "1.15.0"
