name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        cmd:
          - build --all-targets --verbose
          - build --all-targets --release --verbose
          - test --all-features --verbose
          - clippy --all-targets --all-features
          - doc --no-deps --all-features --document-private-items
          - fmt --check
        exclude:
          - os: windows-latest
            cmd: clippy --all-features
          - os: macos-latest
            cmd: clippy --all-features
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions: {}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - run: sudo apt update && sudo apt install -y libfontconfig1-dev libgl1-mesa-dev
        if: runner.os == 'Linux'
      - run: cargo ${{ matrix.cmd }}
